[project]
name = "sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.2"
dependencies = [
    "mcp[cli]>=1.3.0",
    "mysqlclient>=2.2.7",
]
